/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctascontablesypolizas;

import ctascontablesypolizas.Datos.HiloCargarSaldosCuentas;
import ctascontablesypolizas.clases.CrearConexionFBoSQL;
import ctascontablesypolizas.clases.EjercicioEntity;
import ctascontablesypolizas.clases.HiloCExporSaldosIniciales;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ELI
 */
public class frmImportarSaldosIniciales extends javax.swing.JDialog {

    String controlador;
    String servidor;
    int puerto;
    String RutaonombreBDCont;
    String usuario;
    String contrasenia;
    public String puertoCOI;
    public String contraseniaCOI;
    public String usuarioCOI;
    public String tipoCCOI;
    public String servidorCOI;
    public String RutaonombreBDCOI;
    public String controladorCOI;
    public Connection conexionCOI;
    GUIPrincipal padre;
    private boolean bandDoc;
    private String comodin;
    java.util.List olist;
    private Connection conexion;
    String noEmpre;
    private final DefaultTableModel modelo;
    boolean seguridadIntegrada;

    /**
     * Creates new form frmImportarSaldosIniciales
     */
    public frmImportarSaldosIniciales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        modelo = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtnPrimerEjercicio = new javax.swing.JRadioButton();
        rbtnSeleccionado = new javax.swing.JRadioButton();
        cboEjercicios = new javax.swing.JComboBox();
        btnVerSaldosIniciales = new javax.swing.JButton();
        btnTransferirSaldos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pbProgreso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Importar saldos iniciales a ASPEL COI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Seleccionar modo de importación de saldos"));

        buttonGroup1.add(rbtnPrimerEjercicio);
        rbtnPrimerEjercicio.setSelected(true);
        rbtnPrimerEjercicio.setText("En base al primer ejercicio");
        rbtnPrimerEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPrimerEjercicioActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnSeleccionado);
        rbtnSeleccionado.setText("En base al ejercicio seleccionado");
        rbtnSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSeleccionadoActionPerformed(evt);
            }
        });

        cboEjercicios.setEnabled(false);

        btnVerSaldosIniciales.setText("Mostrar registros");
        btnVerSaldosIniciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSaldosInicialesActionPerformed(evt);
            }
        });

        btnTransferirSaldos.setText("Transferir a COI");
        btnTransferirSaldos.setEnabled(false);
        btnTransferirSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirSaldosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnPrimerEjercicio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnSeleccionado)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(cboEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(btnVerSaldosIniciales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTransferirSaldos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVerSaldosIniciales, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTransferirSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnPrimerEjercicio)
                        .addGap(15, 15, 15)
                        .addComponent(rbtnSeleccionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Saldo Inicial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(pbProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            CrearConexionFBoSQL objConexion = new CrearConexionFBoSQL(controlador, servidor, puerto,
                    RutaonombreBDCont, usuario, contrasenia,seguridadIntegrada);
            conexion = objConexion.getConexion();

            if (conexion != null) {
                if (controlador.equals("DevartSQLServer")) {
                    Statement stmt = conexion.createStatement();
                    ResultSet rs = stmt.executeQuery("Select Id,Ejercicio from Ejercicios order by Id");
                    while (rs.next()) {
                        cboEjercicios.addItem(new EjercicioEntity(rs.getInt(1), rs.getString(2)));
                    }
                    rs.close();
                    conexion.close();
                }
                if (cboEjercicios.getItemCount() > 0) {
                    rbtnPrimerEjercicio.setEnabled(true);
                    rbtnSeleccionado.setEnabled(true);
                } else {
                    rbtnPrimerEjercicio.setEnabled(false);
                    rbtnSeleccionado.setEnabled(false);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnVerSaldosInicialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSaldosInicialesActionPerformed
        // TODO add your handling code here:
        try {
            HiloCargarSaldosCuentas hiloCargarSaldos = new HiloCargarSaldosCuentas(btnTransferirSaldos, rbtnPrimerEjercicio.isSelected(),
                    btnVerSaldosIniciales, (EjercicioEntity) cboEjercicios.getSelectedItem(), jTable1, pbProgreso, modelo, controlador,
                    servidor, puerto, usuario, contrasenia,RutaonombreBDCont,seguridadIntegrada);
            hiloCargarSaldos.start();
        } catch (Exception e) {
        }        
    }//GEN-LAST:event_btnVerSaldosInicialesActionPerformed

    private void rbtnSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSeleccionadoActionPerformed
        // TODO add your handling code here:
        if(rbtnSeleccionado.isSelected())
        {
            cboEjercicios.setEnabled(true);
        }
        else{
            cboEjercicios.setEnabled(false);
            cboEjercicios.setSelectedIndex(0);
        }
    }//GEN-LAST:event_rbtnSeleccionadoActionPerformed

    private void rbtnPrimerEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPrimerEjercicioActionPerformed
        // TODO add your handling code here:
        if(rbtnSeleccionado.isSelected())
        {
            cboEjercicios.setEnabled(true);
        }
        else{
            cboEjercicios.setEnabled(false);
            cboEjercicios.setSelectedIndex(0);
        }
    }//GEN-LAST:event_rbtnPrimerEjercicioActionPerformed

    private void btnTransferirSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirSaldosActionPerformed
        // TODO add your handling code here:
        HiloCExporSaldosIniciales hiloExportarSaldos=new HiloCExporSaldosIniciales((EjercicioEntity)cboEjercicios.getSelectedItem(), jTable1,
                noEmpre, btnVerSaldosIniciales, btnTransferirSaldos, pbProgreso, controladorCOI, servidorCOI, Integer.parseInt(puertoCOI), usuarioCOI, contraseniaCOI, RutaonombreBDCOI);
        hiloExportarSaldos.start();
    }//GEN-LAST:event_btnTransferirSaldosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmImportarSaldosIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmImportarSaldosIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmImportarSaldosIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmImportarSaldosIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmImportarSaldosIniciales dialog = new frmImportarSaldosIniciales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferirSaldos;
    private javax.swing.JButton btnVerSaldosIniciales;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboEjercicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JProgressBar pbProgreso;
    private javax.swing.JRadioButton rbtnPrimerEjercicio;
    private javax.swing.JRadioButton rbtnSeleccionado;
    // End of variables declaration//GEN-END:variables
}
