/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctascontablesypolizas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ELI
 */
public class frmTiposPoliza extends javax.swing.JInternalFrame {
    private DefaultTableModel dtmModelo;

    /**
     * Creates new form frmTiposPoliza
     */
    public frmTiposPoliza() {
        initComponents();
        initCustomComponents();
    }
    public void initCustomComponents(){
        dtmModelo = (DefaultTableModel) tblTiposPol.getModel();
        int[] anchosColsTabla = new int[]{50, 150, 40};
        for (int i = 0; i < anchosColsTabla.length; i++) {
            tblTiposPol.getColumnModel().getColumn(i).setPreferredWidth(anchosColsTabla[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiposPol = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jbtnAceptar = new javax.swing.JButton();
        jbtnExportarAContpaq = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Tipos de póliza");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/polcontcoi.png"))); // NOI18N

        tblTiposPol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Clave Contpaq", "Descripción Contpaq", "Clave COI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTiposPol);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setBackground(new java.awt.Color(178, 233, 187));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbtnAceptar.setBackground(new java.awt.Color(178, 233, 187));
        jbtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar2.png"))); // NOI18N
        jbtnAceptar.setToolTipText("Guardar cambios");
        jbtnAceptar.setFocusable(false);
        jbtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnAceptar);

        jbtnExportarAContpaq.setBackground(new java.awt.Color(178, 233, 187));
        jbtnExportarAContpaq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Transferir.png"))); // NOI18N
        jbtnExportarAContpaq.setToolTipText("Transferir a ASPEL COI");
        jbtnExportarAContpaq.setFocusable(false);
        jbtnExportarAContpaq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnExportarAContpaq.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnExportarAContpaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExportarAContpaqActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnExportarAContpaq);

        jBtnSalir.setBackground(new java.awt.Color(178, 233, 187));
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jBtnSalir.setToolTipText("Cerrar");
        jBtnSalir.setFocusable(false);
        jBtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        // TODO add your handling code here:
//        try {
//            Object[] seleccionados = jLstMovtos.getSelectedValues();
//
//            this.dispose();
//            padre.setVisible(true);
//            padre.setSelected(true);
//            padre.jbtnTransferir.setEnabled(false);
//            try {
//                HiloExportCtas miHilo = new HiloExportCtas(noEmpresa,seleccionados, padre.jbtnTransferir,
//                    padre.tiposCtas, padre.jtblCatCtas,
//                    padre.jpbProgreso, padre.modelonuevo,
//                    padre.controlador, padre.servidor, padre.puerto, padre.usuario, padre.contrasenia, padre.RutaonombreBDCont,
//                    padre.controladorCOI, padre.servidorCOI, Integer.parseInt(padre.puertoCOI), padre.usuarioCOI, padre.contraseniaCOI, padre.RutaonombreBDCOI,padre.seguridadIntegrada);
//                miHilo.start();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
//        try {
//            this.dispose();
//            padre.setVisible(true);
//            padre.setSelected(true);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jbtnExportarAContpaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExportarAContpaqActionPerformed
        // TODO add your handling code here:
//        try {
//            exportarPolizas("Adjuntar");
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_jbtnExportarAContpaqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnExportarAContpaq;
    private javax.swing.JTable tblTiposPol;
    // End of variables declaration//GEN-END:variables
}
