/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ctascontablesypolizas;

import ctascontablesypolizas.clases.CrearConexionFBoSQL;
import ctascontablesypolizas.clases.Banda;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

/**
 *
 * @author Gabriel
 */
public class InterfaseContpaqi extends javax.swing.JInternalFrame {

    String controlador;
    String servidor;
    int puerto;
    String RutaonombreBDCont;
    String usuario;
    String contrasenia;
    ListadoPolizas padre;
    private boolean bandDoc;
    private String comodin;
    java.util.List olist;
    private Connection conexion;
    String noEmpre;
    boolean seguridadIntegrada;

    /**
     * Creates new form InterfaseASPELCOI
     */
    public InterfaseContpaqi() {
        initComponents();
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(KeyEvent ke) {
                if (ke.getID() == java.awt.event.KeyEvent.KEY_RELEASED && ke.getKeyCode() == java.awt.event.KeyEvent.VK_F2) {
                    if (jtxtDocumentoDesde.hasFocus()) {
                        abrirDocumentos("jtxtDocumentoDesde", jtxtDocumentoDesde.getText());
                    } else if (jtxtDocumentoHasta.hasFocus()) {
                        abrirDocumentos("jtxtDocumentoHasta", jtxtDocumentoHasta.getText());
                    }
                }
//                if (ke.getID() == java.awt.event.KeyEvent.KEY_RELEASED && ke.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
//                    padre.setVisible(true);
//                    dispose();
//                }
                return false;
            }
        });
        jList1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCBTipoPoliza = new javax.swing.JComboBox();
        jchIngreso = new javax.swing.JCheckBox();
        jchEgreso = new javax.swing.JCheckBox();
        jchDiario = new javax.swing.JCheckBox();
        jchOrden = new javax.swing.JCheckBox();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnSiguiente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnSalir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jlblmesselect = new javax.swing.JLabel();
        jcbEjercicios = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jBtnBuscarDocumentoDesde = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtDocumentoHasta = new javax.swing.JTextField();
        jBtnBuscarDocumentoHasta = new javax.swing.JButton();
        jtxtDocumentoDesde = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Filtrado para pólizas de Contpaq i®");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/polcontcoi.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de póliza"));

        jCBTipoPoliza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingreso", "Egreso", "Diario", "Cheque" }));
        jCBTipoPoliza.setEnabled(false);
        jCBTipoPoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoPolizaActionPerformed(evt);
            }
        });

        jchIngreso.setText("Ingreso");
        jchIngreso.setEnabled(false);

        jchEgreso.setText("Egreso");
        jchEgreso.setEnabled(false);

        jchDiario.setText("Diario");
        jchDiario.setEnabled(false);

        jchOrden.setText("Cheque");
        jchOrden.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jCBTipoPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jchIngreso)
                        .addGap(18, 18, 18)
                        .addComponent(jchEgreso)
                        .addGap(18, 18, 18)
                        .addComponent(jchDiario)
                        .addGap(18, 18, 18)
                        .addComponent(jchOrden)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCBTipoPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchIngreso)
                    .addComponent(jchEgreso)
                    .addComponent(jchDiario)
                    .addComponent(jchOrden))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jToolBar1.setBackground(new java.awt.Color(178, 233, 187));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jBtnSiguiente.setBackground(new java.awt.Color(178, 233, 187));
        jBtnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar2.png"))); // NOI18N
        jBtnSiguiente.setToolTipText("Aceptar");
        jBtnSiguiente.setEnabled(false);
        jBtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSiguienteActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnSiguiente);
        jToolBar1.add(jSeparator1);

        jBtnSalir.setBackground(new java.awt.Color(178, 233, 187));
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jBtnSalir.setToolTipText("Salir");
        jBtnSalir.setFocusable(false);
        jBtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnSalir);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Período y Ejercicio"));

        jLabel2.setText("Ejercicio:");

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jlblmesselect.setText("Período(s): ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlblmesselect, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblmesselect))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Rango de pólizas"));

        jLabel5.setText("Desde:");

        jBtnBuscarDocumentoDesde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jBtnBuscarDocumentoDesde.setToolTipText("Buscar Documento");
        jBtnBuscarDocumentoDesde.setEnabled(false);
        jBtnBuscarDocumentoDesde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jBtnBuscarDocumentoDesdeFocusLost(evt);
            }
        });
        jBtnBuscarDocumentoDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarDocumentoDesdeActionPerformed(evt);
            }
        });

        jLabel6.setText("Hasta:");

        jtxtDocumentoHasta.setEditable(false);
        jtxtDocumentoHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDocumentoHastaActionPerformed(evt);
            }
        });
        jtxtDocumentoHasta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtDocumentoHastaFocusLost(evt);
            }
        });
        jtxtDocumentoHasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtDocumentoHastaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDocumentoHastaKeyTyped(evt);
            }
        });

        jBtnBuscarDocumentoHasta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jBtnBuscarDocumentoHasta.setToolTipText("Buscar Documento");
        jBtnBuscarDocumentoHasta.setEnabled(false);
        jBtnBuscarDocumentoHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarDocumentoHastaActionPerformed(evt);
            }
        });
        jBtnBuscarDocumentoHasta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jBtnBuscarDocumentoHastaFocusLost(evt);
            }
        });

        jtxtDocumentoDesde.setEnabled(false);
        jtxtDocumentoDesde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDocumentoDesdeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtDocumentoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnBuscarDocumentoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtDocumentoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtnBuscarDocumentoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jtxtDocumentoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jBtnBuscarDocumentoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBtnBuscarDocumentoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jtxtDocumentoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Filtro de pólizas", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void abrirDocumentos(String txt, String filtroInicial) {
        try {
            if (conexion != null) {
                Documentos ventana = new Documentos(null, true);
                ventana.conexion = this.conexion;
                ventana.padre = this;
                ventana.cajaTexto = txt;
                ventana.filtroTipos = this.getSQLPeriodos();
                ventana.filtroPeriodos = this.getPeridos();
                ventana.filtroInicial = filtroInicial;
                ventana.setVisible(true);
            } else {
                if (conexion != null) {
                    conexion.close();
                }
                JOptionPane.showMessageDialog(this, "Seleccione una base de datos para trabajar", "No ha seleccionado una base de datos", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String getPeridos() {
        Object[] seleccionados = jList1.getSelectedValues();
        int lim = seleccionados.length;
        String completo = "AND (pol.Periodo=";
        if (lim != 0) {
            for (int i = 0; i < lim; i++) {
                Banda banda = (Banda) seleccionados[i];
                String id = banda.getId();
                completo += id + " OR pol.Periodo=";
            }
            completo = completo.substring(0, completo.length() - 16) + ")";
        } else {
//            JOptionPane.showMessageDialog(this, "Debes seleccionar al menos un perìodo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jList1.requestFocus();
        }
        return completo;
    }
    private void jBtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSiguienteActionPerformed
        //your code here
        Object[] seleccionados = jList1.getSelectedValues();
        int lim = seleccionados.length;
        if (lim != 0) {
            crearPoliza(getPeridos());
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar al menos un perìodo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jList1.requestFocus();
        }
    }//GEN-LAST:event_jBtnSiguienteActionPerformed

    public void crearPoliza(String periodos) {//01-05-13 fecha de prueba
        try {
            Statement stmt = conexion.createStatement();
            String sqlInicial = "Select count(*) from dbo.Polizas pol "
                    + " where (pol.Ejercicio=" + jcbEjercicios.getSelectedItem() + ") " + periodos;
            if (!jtxtDocumentoDesde.getText().equalsIgnoreCase("") && !jtxtDocumentoHasta.getText().equalsIgnoreCase("")) {
                sqlInicial += " AND (pol.Folio between " + jtxtDocumentoDesde.getText().trim() + " AND " + jtxtDocumentoHasta.getText().trim() + ")";//Rango de productos
            } else if (!jtxtDocumentoDesde.getText().equalsIgnoreCase("") && jtxtDocumentoHasta.getText().equalsIgnoreCase("")) {
                sqlInicial += " AND pol.Folio>=" + jtxtDocumentoDesde.getText().trim() + "";//productos desde 32323 hasta el final
            } else if (jtxtDocumentoDesde.getText().equalsIgnoreCase("") && !jtxtDocumentoHasta.getText().equalsIgnoreCase("")) {
                sqlInicial += " AND pol.Folio<=" + jtxtDocumentoHasta.getText().trim() + "";//productos desde el inicio asta 3453543
            }
            if (jCBTipoPoliza.getSelectedIndex() == 0) {//ingreso
                sqlInicial += " AND (pol.TipoPol=1";
                if (jchEgreso.isSelected()) {
                    sqlInicial += " or pol.TipoPol=2";
                }
                if (jchDiario.isSelected()) {
                    sqlInicial += " or pol.TipoPol=3";
                }
                sqlInicial += ")";
            } else if (jCBTipoPoliza.getSelectedIndex() == 1) {//egreso
                sqlInicial += " AND (pol.TipoPol=2";
                if (jchIngreso.isSelected()) {
                    sqlInicial += " or pol.TipoPol=1";
                }
                if (jchDiario.isSelected()) {
                    sqlInicial += " or pol.TipoPol=3";
                }
                sqlInicial += ")";
            } else if (jCBTipoPoliza.getSelectedIndex() == 2) {//diario
                sqlInicial += " AND (pol.TipoPol=3";
                if (jchIngreso.isSelected()) {
                    sqlInicial += " or pol.TipoPol=1";
                }
                if (jchEgreso.isSelected()) {
                    sqlInicial += " or pol.TipoPol=2";
                }
                sqlInicial += ")";
            } else if (jCBTipoPoliza.getSelectedIndex() == 3) {//cheque
                sqlInicial += " AND (pol.TipoPol=6";
                if (jchIngreso.isSelected()) {
                    sqlInicial += " or pol.TipoPol=1";
                }
                if (jchEgreso.isSelected()) {
                    sqlInicial += " or pol.TipoPol=2";
                }
                if (jchDiario.isSelected()) {
                    sqlInicial += " or pol.TipoPol=3";
                }
                sqlInicial += ")";
            }
//            JOptionPane.showMessageDialog(this, sqlInicial);

            ResultSet ResulSet = stmt.executeQuery(sqlInicial);
            int numRegDocs = 0;
            if (ResulSet.next()) {
                numRegDocs = ResulSet.getInt(1);
            }
            if (numRegDocs <= 0) {
                JOptionPane.showMessageDialog(this, "No existen polizas para el filtro aplicado \n"
                        + "NOTA: El documento final no debe ser menor al inicial", "Sin registros", JOptionPane.ERROR_MESSAGE);
                jtxtDocumentoDesde.requestFocus();
                bandDoc = false;
            } else {
                bandDoc = true;
            }
            if (jtxtDocumentoDesde.getText().equalsIgnoreCase("") || jtxtDocumentoHasta.getText().equalsIgnoreCase("")) {
                bandDoc = true;
            }
            if (bandDoc) {

                String SQlAprobar = "";
                SQlAprobar = armarSQL(periodos);
//                JOptionPane.showMessageDialog(this, SQlAprobar);
                ResultSet RstCount = stmt.executeQuery(SQlAprobar);
                int contador = 0;
                while (RstCount.next()) {
                    contador++;
                }
                RstCount.close();
                if (contador <= 0) {
                    JOptionPane.showMessageDialog(this, "No existen registros para el filtro aplicado", "Sin registros", JOptionPane.ERROR_MESSAGE);
                    jBtnSiguiente.requestFocus();
                } else {
                    /*
                     * Se refresca la tabla de la ventana litado de polizas
                     * y se ace visible la ventana padre y se cierra la actual
                     */
                    conexion.close();
                    padre.llenarTabla(olist, SQlAprobar, contador, Integer.parseInt(jcbEjercicios.getSelectedItem().toString()), true);
                    padre.setVisible(true);
                    this.dispose();

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String armarSQL(String periodos) {
        String Sql = "";
               try {
            Sql = "Select "
                    + " pol.Id,"
                    + " pol.Periodo,"
                    + "pol.TipoPol,"
                    + "pol.Folio,"
                    + "pol.Concepto,"
                    + "pol.Fecha,"
                    + "pol.Cargos,"
                    + "pol.Abonos"
                    + " from dbo.Polizas pol"
                    + " Where (pol.Ejercicio=" + jcbEjercicios.getSelectedItem() + ") " + periodos + " ";

            if (!jtxtDocumentoDesde.getText().equalsIgnoreCase("") && !jtxtDocumentoHasta.getText().equalsIgnoreCase("")) {
                Sql += " AND (pol.Folio between " + jtxtDocumentoDesde.getText().trim() + " AND " + jtxtDocumentoHasta.getText().trim() + ")";//Rango de productos
            } else if (!jtxtDocumentoDesde.getText().equalsIgnoreCase("") && jtxtDocumentoHasta.getText().equalsIgnoreCase("")) {
                Sql += " AND pol.Folio>=" + jtxtDocumentoDesde.getText().trim() + "";//productos desde 32323 hasta el final
            } else if (jtxtDocumentoDesde.getText().equalsIgnoreCase("") && !jtxtDocumentoHasta.getText().equalsIgnoreCase("")) {
                Sql += " AND pol.Folio<=" + jtxtDocumentoHasta.getText().trim() + "";//productos desde el inicio asta 3453543
            }

            if (jCBTipoPoliza.getSelectedIndex() == 0) {//ingreso
                Sql += " AND (pol.TipoPol=1";
                if (jchEgreso.isSelected()) {
                    Sql += " or pol.TipoPol=2";
                }
                if (jchDiario.isSelected()) {
                    Sql += " or pol.TipoPol=3";
                }
                Sql += ")";
            } else if (jCBTipoPoliza.getSelectedIndex() == 1) {//egreso
                Sql += " AND (pol.TipoPol=2";
                if (jchIngreso.isSelected()) {
                    Sql += " or pol.TipoPol=1";
                }
                if (jchDiario.isSelected()) {
                    Sql += " or pol.TipoPol=3";
                }
                Sql += ")";
            } else if (jCBTipoPoliza.getSelectedIndex() == 2) {//diario
                Sql += " AND (pol.TipoPol=3";
                if (jchIngreso.isSelected()) {
                    Sql += " or pol.TipoPol=1";
                }
                if (jchEgreso.isSelected()) {
                    Sql += " or pol.TipoPol=2";
                }
                Sql += ")";
            } else if (jCBTipoPoliza.getSelectedIndex() == 3) {//orden
                Sql += " AND (pol.TipoPol=6";
                if (jchIngreso.isSelected()) {
                    Sql += " or pol.TipoPol=1";
                }
                if (jchEgreso.isSelected()) {
                    Sql += " or pol.TipoPol=2";
                }
                if (jchDiario.isSelected()) {
                    Sql += " or pol.TipoPol=3";
                }
                Sql += ")";
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return Sql;
    }

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
            padre.setVisible(true);
            padre.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtnSalirActionPerformed
    public void configurarList() {
        try {
            DefaultListModel lm = new DefaultListModel();
            lm.addElement(new Banda("Enero", "1"));
            lm.addElement(new Banda("Febrero", "2"));
            lm.addElement(new Banda("Marzo", "3"));
            lm.addElement(new Banda("Abril", "4"));
            lm.addElement(new Banda("Mayo", "5"));
            lm.addElement(new Banda("Junio", "6"));
            lm.addElement(new Banda("Julio", "7"));
            lm.addElement(new Banda("Agosto", "8"));
            lm.addElement(new Banda("Septiembre", "9"));
            lm.addElement(new Banda("Octubre", "10"));
            lm.addElement(new Banda("Noviembre", "11"));
            lm.addElement(new Banda("Diciembre", "12"));
            lm.addElement(new Banda("Ajuste", "14"));
            jList1.setModel(lm);
            jList1.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            configurarList();
            this.setLocation(this.getParent().getWidth() / 2 - this.getWidth() / 2, this.getParent().getHeight() / 2 - this.getHeight() / 2 - 20);
            CrearConexionFBoSQL objConexion = new CrearConexionFBoSQL(controlador, servidor, puerto,
                    RutaonombreBDCont, usuario, contrasenia,seguridadIntegrada);
            conexion = objConexion.getConexion();
           
            if (conexion != null) {
                if (controlador.equals("DevartSQLServer")) {
                    Statement stmt = conexion.createStatement();
                    ResultSet rs = stmt.executeQuery("Select Ejercicio from Ejercicios");
                    while (rs.next()) {
                        jcbEjercicios.addItem(rs.getInt(1));
                    }
                    rs.close();
                }
                jtxtDocumentoDesde.setEnabled(true);
                jBtnBuscarDocumentoDesde.setEnabled(true);
                jBtnBuscarDocumentoHasta.setEnabled(true);
                jtxtDocumentoDesde.setEditable(true);
                jtxtDocumentoHasta.setEditable(true);
                jBtnSiguiente.setEnabled(true);
                jcbEjercicios.setEnabled(true);
                jCBTipoPoliza.setEnabled(true);
                jchIngreso.setEnabled(true);
                jchIngreso.setVisible(false);
                jchEgreso.setEnabled(true);
                jchDiario.setEnabled(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

    public String completaComodin(String folio) {
        String folioReal = (folio + "");
        while (folioReal.length() < 5) {
            folioReal = folioReal + "?";
        }
        return folioReal;
    }
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        try {
            this.dispose();
            padre.setVisible(true);
            padre.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void jBtnBuscarDocumentoHastaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBtnBuscarDocumentoHastaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBuscarDocumentoHastaFocusLost

    private void jBtnBuscarDocumentoHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarDocumentoHastaActionPerformed
        // TODO add your handling code here:
        abrirDocumentos("jtxtDocumentoHasta", jtxtDocumentoHasta.getText());
    }//GEN-LAST:event_jBtnBuscarDocumentoHastaActionPerformed

    private void jtxtDocumentoHastaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDocumentoHastaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDocumentoHastaKeyReleased

    private void jtxtDocumentoHastaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDocumentoHastaFocusLost
        // TODO add your handling code here:
        //        if (!evt.isTemporary()) {
        //            String content = jtxtDocumentoHasta.getText();
        //            if (!content.trim().equalsIgnoreCase("")) {
        //                if (!validarAlmacen(content)) {
        //                    JOptionPane.showMessageDialog(this, "El almacen no existe");
        //                    SwingUtilities.invokeLater(new FocusGrabber(jtxtDocumentoHasta));
        //                    jtxtDocumentoHasta.setBackground(new Color(178, 233, 187));
        //                    jtxtDocumentoHasta.requestFocus();
        //                } else {
        //                    jtxtDocumentoHasta.setBackground(Color.white);
        //                }
        //            }
        //        }
    }//GEN-LAST:event_jtxtDocumentoHastaFocusLost

    private void jtxtDocumentoHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDocumentoHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDocumentoHastaActionPerformed

    private void jBtnBuscarDocumentoDesdeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBtnBuscarDocumentoDesdeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBuscarDocumentoDesdeFocusLost

    private void jBtnBuscarDocumentoDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarDocumentoDesdeActionPerformed
        // TODO add your handling code here:
        abrirDocumentos("jtxtDocumentoDesde", jtxtDocumentoDesde.getText());
    }//GEN-LAST:event_jBtnBuscarDocumentoDesdeActionPerformed
    public String getSQLPeriodos() {
        String periodos = "";
        if (jCBTipoPoliza.getSelectedIndex() == 0) {//ingreso
            periodos += " (pol.TipoPol=1";
            if (jchEgreso.isSelected()) {
                periodos += " or pol.TipoPol=2";
            }
            if (jchDiario.isSelected()) {
                periodos += " or pol.TipoPol=3";
            }
            if (jchOrden.isSelected()) {
                periodos += " or pol.TipoPol=4";
            }
            periodos += ") AND pol.Ejercicio=" + jcbEjercicios.getSelectedItem();
        } else if (jCBTipoPoliza.getSelectedIndex() == 1) {//egreso
            periodos += " (pol.TipoPol=2";
            if (jchIngreso.isSelected()) {
                periodos += " or pol.TipoPol=1";
            }
            if (jchDiario.isSelected()) {
                periodos += " or pol.TipoPol=3";
            }
            if (jchOrden.isSelected()) {
                periodos += " or pol.TipoPol=4";
            }
            periodos += ") AND pol.Ejercicio=" + jcbEjercicios.getSelectedItem();
        } else if (jCBTipoPoliza.getSelectedIndex() == 2) {//diario
            periodos += " (pol.TipoPol=3";
            if (jchIngreso.isSelected()) {
                periodos += " or pol.TipoPol=1";
            }
            if (jchEgreso.isSelected()) {
                periodos += " or pol.TipoPol=2";
            }
            if (jchOrden.isSelected()) {
                periodos += " or pol.TipoPol=4";
            }
            periodos += ") AND pol.Ejercicio=" + jcbEjercicios.getSelectedItem();
        } else if (jCBTipoPoliza.getSelectedIndex() == 3) {//Orden
            periodos += " (pol.TipoPol=6";
            if (jchIngreso.isSelected()) {
                periodos += " or pol.TipoPol=1";
            }
            if (jchEgreso.isSelected()) {
                periodos += " or pol.TipoPol=2";
            }
            if (jchDiario.isSelected()) {
                periodos += " or pol.TipoPol=3";
            }
            periodos += ") AND pol.Ejercicio=" + jcbEjercicios.getSelectedItem();
        }
        return periodos;
    }
    private void jtxtDocumentoHastaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDocumentoHastaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtDocumentoHastaKeyTyped

    private void jCBTipoPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoPolizaActionPerformed
        // TODO add your handling code here:
        if (jCBTipoPoliza.getSelectedIndex() == 0) {
            jchIngreso.setVisible(false);
            jchEgreso.setVisible(true);
            jchEgreso.setSelected(false);
            jchDiario.setVisible(true);
            jchDiario.setSelected(false);
        } else if (jCBTipoPoliza.getSelectedIndex() == 1) {
            jchEgreso.setVisible(false);
            jchIngreso.setVisible(true);
            jchIngreso.setSelected(false);
            jchDiario.setVisible(true);
            jchDiario.setSelected(false);
        } else if (jCBTipoPoliza.getSelectedIndex() == 2) {
            jchDiario.setVisible(false);
            jchIngreso.setVisible(true);
            jchIngreso.setSelected(false);
            jchEgreso.setVisible(true);
            jchEgreso.setSelected(false);
        } else if (jCBTipoPoliza.getSelectedIndex() == 3) {//cheque
            jchOrden.setVisible(false);
            jchDiario.setVisible(true);
            jchDiario.setSelected(false);
            jchIngreso.setVisible(true);
            jchIngreso.setSelected(false);
            jchEgreso.setVisible(true);
            jchEgreso.setSelected(false);
        }
    }//GEN-LAST:event_jCBTipoPolizaActionPerformed

    private void jtxtDocumentoDesdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDocumentoDesdeKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtDocumentoDesdeKeyTyped

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        Object[] seleccionados = jList1.getSelectedValues();
        int lim = seleccionados.length;
        String completo = "";
        if (lim != 0) {
            for (int i = 0; i < lim; i++) {
                Banda banda = (Banda) seleccionados[i];
                String id = banda.getId();
                completo += id + ",";
            }
            jlblmesselect.setText("Período(s): " + completo.substring(0, completo.length() - 1));
        }
    }//GEN-LAST:event_jList1ValueChanged

    public void limpiarCampos() {
        try {
            jtxtDocumentoDesde.setText("");
            jtxtDocumentoHasta.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarDocumentoDesde;
    private javax.swing.JButton jBtnBuscarDocumentoHasta;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnSiguiente;
    protected javax.swing.JComboBox jCBTipoPoliza;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox jcbEjercicios;
    private javax.swing.JCheckBox jchDiario;
    private javax.swing.JCheckBox jchEgreso;
    private javax.swing.JCheckBox jchIngreso;
    private javax.swing.JCheckBox jchOrden;
    private javax.swing.JLabel jlblmesselect;
    protected javax.swing.JTextField jtxtDocumentoDesde;
    protected javax.swing.JTextField jtxtDocumentoHasta;
    // End of variables declaration//GEN-END:variables
}
